# Generated by Django 4.0.3 on 2022-04-13 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import story_account.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='empty', max_length=150)),
                ('lastname', models.CharField(default='empty', max_length=150)),
                ('email', models.EmailField(default='empty', max_length=150)),
                ('slogan', models.CharField(default='empty', max_length=150)),
                ('text', models.TextField(default='empty')),
                ('image', models.ImageField(blank=True, null=True, upload_to=story_account.models.upload_image_path)),
                ('author', models.ForeignKey(default='empty', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
