# Generated by Django 4.0.3 on 2022-04-13 19:15

from django.db import migrations, models
import story_about.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Siteabout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('about_us', models.TextField(blank=True, null=True)),
                ('programmer_image', models.ImageField(blank=True, null=True, upload_to=story_about.models.upload_image_path)),
            ],
        ),
    ]
